// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface AboutPageContent {
  id: string;
  slug: string | null;
  status: string;
  hero_heading: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  history_heading?: string;
  history_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  history_body?: PortableTextBlock[];
  history_cta1_label?: string;
  history_cta1_href?: string;
  history_cta2_label?: string;
  history_cta2_href?: string;
  cta_bar_heading?: string;
  cta_bar_label?: string;
  cta_bar_href?: string;
  credits_left_body?: PortableTextBlock[];
  credits_right_body?: PortableTextBlock[];
  credits_cta_label?: string;
  credits_cta_href?: string;
  tubman_heading?: string;
  tubman_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  tubman_body?: PortableTextBlock[];
  testimonial_quote?: string;
  testimonial_attribution?: string;
  gallery_image_1?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  gallery_image_2?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  gallery_image_3?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  gallery_image_4?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ContactPageContent {
  id: string;
  slug: string | null;
  status: string;
  hero_heading: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  address_body?: PortableTextBlock[];
  map_embed_url?: string;
  form_heading?: string;
  form_intro?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Event {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  starts_at: string;
  ends_at?: string;
  time_text?: string;
  location?: string;
  summary?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  cta_label?: string;
  cta_href?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface EventsPageContent {
  id: string;
  slug: string | null;
  status: string;
  hero_heading: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  events_section_heading?: string;
  events_section_intro?: string;
  events_max?: number;
  events_view_all_label?: string;
  events_view_all_href?: string;
  annual_events_heading?: string;
  annual_events_intro?: string;
  host_left_heading?: string;
  host_left_body?: PortableTextBlock[];
  host_left_cta_label?: string;
  host_left_cta_href?: string;
  host_right_heading?: string;
  host_right_body?: PortableTextBlock[];
  host_right_cta_label?: string;
  host_right_cta_href?: string;
  newsletter_heading?: string;
  newsletter_subheading?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface FriendsPageContent {
  id: string;
  slug: string | null;
  status: string;
  hero_heading: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  lead_paragraph?: string;
  history_heading?: string;
  history_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  history_body?: PortableTextBlock[];
  history_cta_label?: string;
  history_cta_href?: string;
  board_heading?: string;
  board_intro?: string;
  mission_heading?: string;
  mission_subheading?: string;
  mission_body?: PortableTextBlock[];
  video_youtube_id?: string;
  video_title?: string;
  video_caption?: string;
  projects_heading?: string;
  projects_intro?: string;
  partners_heading?: string;
  testimonial_quote?: string;
  testimonial_attribution?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface GetInvolvedPageContent {
  id: string;
  slug: string | null;
  status: string;
  hero_heading: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  lead_paragraph?: string;
  donate_heading?: string;
  donate_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  donate_body?: PortableTextBlock[];
  donate_cta_label?: string;
  donate_cta_href?: string;
  volunteer_heading?: string;
  volunteer_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  volunteer_body?: PortableTextBlock[];
  testimonial_quote?: string;
  testimonial_attribution?: string;
  gallery_image_1?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  gallery_image_2?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  gallery_image_3?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  gallery_image_4?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HomepageContent {
  id: string;
  slug: string | null;
  status: string;
  hero_heading: string;
  hero_body?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hero_cta1_label?: string;
  hero_cta1_href?: string;
  hero_cta2_label?: string;
  hero_cta2_href?: string;
  events_section_heading?: string;
  events_section_intro?: string;
  events_view_all_label?: string;
  events_view_all_href?: string;
  discover_heading?: string;
  discover_subheading?: string;
  activity_grid_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  testimonial_quote?: string;
  testimonial_attribution?: string;
  gallery_image_1?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  gallery_image_2?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  gallery_image_3?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  gallery_image_4?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Partner {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  logo: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  url?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface SiteExtras {
  id: string;
  slug: string | null;
  status: string;
  logo_inverse?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  donate_cta_label?: string;
  donate_cta_href?: string;
  contact_email?: string;
  contact_address?: string;
  copyright?: string;
  newsletter_heading?: string;
  newsletter_action?: string;
  newsletter_submit_label?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface BoardMember {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  role?: string;
  photo?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  bio?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    about_content: AboutPageContent;
    contact_content: ContactPageContent;
    events: Event;
    events_page_content: EventsPageContent;
    friends_content: FriendsPageContent;
    get_involved_content: GetInvolvedPageContent;
    homepage_content: HomepageContent;
    partners: Partner;
    site_extras: SiteExtras;
    team_members: BoardMember;
  }
}